name: 'dbt_gold_warehouse'
version: '1.0.0'
config-version: 2

profile: 'gold_warehouse'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_gold_warehouse:
    +materialized: table
    staging:
      +materialized: view